from flask import Flask, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)


food_items = [
    {"id": 1, "name": "Pizza"},
    {"id": 2, "name": "Burger"},
    {"id": 3, "name": "Salad"},
    {"id": 4, "name": "Pasta"},
    {"id": 5, "name": "Sandwich"},
    {"id": 6, "name": "Steak"},
    {"id": 7, "name": "Sushi"},
    {"id": 8, "name": "Tacos"},
    {"id": 9, "name": "Burrito"},
    {"id": 10, "name": "Fried Chicken"},
    {"id": 11, "name": "Hot Dog"},
    {"id": 12, "name": "Ramen"},
    {"id": 13, "name": "Pho"},
    {"id": 14, "name": "Dim Sum"},
    {"id": 15, "name": "Pad Thai"},
    {"id": 16, "name": "Fish and Chips"},
    {"id": 17, "name": "Sushi Burrito"},
    {"id": 18, "name": "Chicken Wings"},
    {"id": 19, "name": "Mongolian Beef"},
    {"id": 20, "name": "Caesar Salad"},
    {"id": 21, "name": "Greek Salad"},
    {"id": 22, "name": "Caprese Salad"},
    {"id": 23, "name": "Macaroni and Cheese"},
    {"id": 24, "name": "Lasagna"},
    {"id": 25, "name": "Calzone"},
    {"id": 26, "name": "Cobb Salad"},
    {"id": 27, "name": "Gyros"},
    {"id": 28, "name": "Shawarma"},
    {"id": 29, "name": "Chow Mein"},
    {"id": 30, "name": "Chicken Tikka Masala"},
    {"id": 31, "name": "Butter Chicken"},
    {"id": 32, "name": "Kebabs"},
    {"id": 33, "name": "Fish Tacos"},
    {"id": 34, "name": "Clam Chowder"},
    {"id": 35, "name": "Crab Cakes"},
    {"id": 36, "name": "Lobster Roll"},
    {"id": 37, "name": "Fish Burger"},
    {"id": 38, "name": "BBQ Ribs"},
    {"id": 39, "name": "Pulled Pork Sandwich"},
    {"id": 40, "name": "Beef Stroganoff"},
    {"id": 41, "name": "Chicken Parmesan"},
    {"id": 42, "name": "Garlic Shrimp"},
    {"id": 43, "name": "Escargot"},
    {"id": 44, "name": "Caviar"},
    {"id": 45, "name": "Foie Gras"},
    {"id": 46, "name": "Buffalo Wings"},
    {"id": 47, "name": "Ribs"},
    {"id": 48, "name": "Nachos"},
    {"id": 49, "name": "Quesadilla"},
    {"id": 50, "name": "Enchiladas"},
    {"id": 51, "name": "Guacamole"},
    {"id": 52, "name": "Churros"},
    {"id": 53, "name": "Empanadas"},
    {"id": 54, "name": "Tamales"},
    {"id": 55, "name": "Pozole"},
    {"id": 56, "name": "Tortilla Soup"},
    {"id": 57, "name": "Flautas"},
    {"id": 58, "name": "Menudo"},
    {"id": 59, "name": "Sopes"},
    {"id": 60, "name": "Ceviche"},
    {"id": 61, "name": "Pupusas"},
    {"id": 62, "name": "Arroz con Pollo"},
    {"id": 63, "name": "Cuban Sandwich"},
    {"id": 64, "name": "Plantain Chips"},
    {"id": 65, "name": "Mofongo"},
    {"id": 66, "name": "Bacalao"},
    {"id": 67, "name": "Asado"},
    {"id": 68, "name": "Chimichurri"},
    {"id": 69, "name": "Milanesa"},
    {"id": 70, "name": "Morcilla"},
    {"id": 71, "name": "Parrillada"},
    {"id": 72, "name": "Choripan"},
    {"id": 73, "name": "Sancocho"},
    {"id": 74, "name": "Pabellón Criollo"},
    {"id": 75, "name": "Arepas"},
    {"id": 76, "name": "Cachapa"},
    {"id": 77, "name": "Hallaca"},
    {"id": 78, "name": "Tostones"},
    {"id": 79, "name": "Carne Mechada"},
    {"id": 80, "name": "Tequeños"},
    {"id": 81, "name": "Papa a la Huancaína"},
    {"id": 82, "name": "Anticuchos"},
    {"id": 83, "name": "Tacu Tacu"},
    {"id": 84, "name": "Lomo Saltado"},
    {"id": 85, "name": "Causa Rellena"},
    {"id": 86, "name": "Rocoto Relleno"},
    {"id": 87, "name": "Aji de Gallina"},
    {"id": 88, "name": "Seco de Res"},
    {"id": 89, "name": "Seco de Cabrito"},
    {"id": 90, "name": "Seco de Chavelo"},
    {"id": 91, "name": "Arroz con Pato"},
    {"id": 92, "name": "Arroz con Mariscos"},
    {"id": 93, "name": "Chaufa"},
    {"id": 94, "name": "Picarones"},
    {"id": 95, "name": "Suspiro a la Limeña"},
    {"id": 96, "name": "Mazamorra Morada"},
    {"id": 97, "name": "Arroz Zambito"},
    {"id": 98, "name": "Turron Doña Pepa"},
    {"id": 99, "name": "Alfajores"},
    {"id": 100, "name": "Dulce de Leche"}
]

@app.route('/api/food_items', methods=['GET'])
def get_food_items():
    return jsonify(food_items)

if __name__ == '__main__':
    app.run(debug=True)
